### ISSUE TITLE
Does not work on Firefox 57

### ISSUE THREAD

**Issue by Poonkraft** [eight04/No-Embed-YouTube#1]
Does not work on Firefox 57.0b6 + Violentmonkey 2.8.10
I know 57 is still beta, but please fix the script so it is ready for 57 launch.
多謝

**Comment by eight04** [comment]
Can't reproduce. Please provide more information e.g. the URL of the page.

**Comment by Poonkraft** [comment]
I did some testing, it is not an issue with your script.
The problem was that uMatrix blocked first party scripts, but that is only a problem with Violentmonkey and Tempermonkey. Greasemonkey does not care if scripts are blocked.
Unfortunately there is no Greasemonkey on 57. I'll try again when there is a new Greasemonkey, but even that may not help with this stupid webextensions.
For now issue can be closed.

**Comment by eight04** [comment]
If you sure the problem is caused by uMatrix + Violentmonkey/Tampermonkey, you can file the issue to them. It is a serious bug that uMatrix would disable userscripts.

**Comment by Poonkraft** [comment]
I think it is worse than that, it is a problem with Firefox, not with uMatrix. It is related to CSP.
Enabling 1st party scripts in uMatrix does not solve the problem on all sites. However, setting security.csp.enable = false will let scripts run on all sites. That is not a desirable setting though.
I also found that mozilla is aware of this CSP problem, they may or may not fix it 58. Until it is solved, I will use an alternative to Firefox.
